<template>
    <div class="container mx-auto mt-6">
        <div class="grid grid-cols-7 gap-2">
            <div class="col-span-3">
                <SearchLocations :options="locations" label="Location" :selected-location="selectedLocation" @selected="handleLocationSelect"/>
            </div>
            <div class="col-span-3">
                <SearchItems :options="items" label="Items" :selected-item="selectedItem" @selected="handleItemSelect"/>
            </div>
            <div class="col-span-1 text-right mt-7 flex justify-start">
                <span class="ml-3 rounded-md shadow-sm">
                    <button type="submit" class="p-3 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out disabled:opacity-25 disabled:cursor-not-allowed" :disabled="Object.entries(selectedLocation).length === 0 || !selectedItem" @click="addHint">
                        Add
                    </button>
                </span>
            </div>
        </div>
        <div class="text-xl text-gray-300 my-4 border-b border-gray-500">
            Known Hints
        </div>
        <ul v-show="regionHints" class="mt-4">
            <li v-for="(hints, region) in regionHints" :key="region" class="mb-2">
                <span class="text-lg text-gray-400">{{ splitRegionName(region) }}</span>
                <ul class="mt-2">
                    <li v-for="(hint, index) in hints" :key="`${hint}-${index}`" class="flex items-center text-gray-300 ml-4">
                        <p class="mr-2">
                            <span>{{ hint.locationName }}</span> is <span>{{ hint.item }}</span>
                        </p>
                        <button class="flex items-center pr-3 text-gray-400 text-red-400 rounded-tr-lg hover:text-red-600 focus:outline-none" @click="removeHint(region, hint)">
                            <svg fill="currentColor" viewBox="0 0 20 20" class="w-5 h-5">
                                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"/>
                            </svg>
                        </button>
                    </li>
                </ul>
            </li>
        </ul>
        <div v-show="!regionHints" class="text-sm text-gray-400">
            Add a hint above to begin...
        </div>

        <div class="mt-8">
            <button class="w-full md:w-auto bg-red-600 px-4 py-2 text-red-100 rounded-lg hover:bg-red-500" @click="showDeleteModal = true">
                Reset
            </button>
        </div>
        <DeleteModal :open="showDeleteModal" @confirm-delete="resetRegionHints" @cancel="showDeleteModal = false"/>
        <!--        <Notification :show="showNotification" :message="message" @close="handleNotificationClose"/>-->
    </div>
</template>

<script>
    import SearchLocations from "./SearchLocations";
    import SearchItems from "./SearchItems";
    import DeleteModal from "./DeleteModal";
    // import Notification from "./Notification";

    export default {
        name: "HintTracker",
        components: {DeleteModal, SearchItems, SearchLocations},
        data() {
            return {
                selectedLocation: {},
                selectedItem: null,
                items: [
                    "5 Bombchu",
                    "10 Arrows",
                    "10 Bombchu",
                    "10 Bombs",
                    "10 Deku Nuts",
                    "30 Arrows",
                    "50 Arrows",
                    "Adult Wallet",
                    "All Night Mask",
                    "Big Bomb Bag",
                    "Biggest Bomb Bag",
                    "Blast Mask",
                    "Blue Potion",
                    "Blue Rupee",
                    "Bomb Bag",
                    "Bombchu",
                    "Bombers' Notebook",
                    "Bottle with Chateau Romani",
                    "Bottle with Gold Dust",
                    "Bottle with Milk",
                    "Bottle with Red Potion",
                    "Bottle: Big Poe",
                    "Bottle: Bug",
                    "Bottle: Deku Princess",
                    "Bottle: Fairy",
                    "Bottle: Fish",
                    "Bottle: Hot Spring Water",
                    "Bottle: Mushroom",
                    "Bottle: Poe",
                    "Bottle: Spring Water",
                    "Bottle: Zora Egg",
                    "Bremen Mask",
                    "Bunny Hood",
                    "Captain's Hat",
                    "Chateau Romani",
                    "Circus Leader's Mask",
                    "Clock Town Stray Fairy",
                    "Couple's Mask",
                    "Deku Mask",
                    "Deku Stick",
                    "Don Gero's Mask",
                    "Double Defense",
                    "Elegy of Emptiness",
                    "Empty Bottle",
                    "Epona's Song",
                    "Extended Magic Power",
                    "Fairy",
                    "Fierce Deity's Mask",
                    "Fire Arrow",
                    "Garo's Mask",
                    "Giant Wallet",
                    "Giant's Mask",
                    "Gibdo Mask",
                    "Gilded Sword",
                    "Gold Rupee",
                    "Goron Lullaby",
                    "Goron Mask",
                    "Great Bay Boss Key",
                    "Great Bay Compass",
                    "Great Bay Map",
                    "Great Bay Small Key",
                    "Great Bay Stray Fairy",
                    "Great Fairy's Mask",
                    "Great Fairy's Sword",
                    "Green Potion",
                    "Heart Container",
                    "Hero's Bow",
                    "Hero's Shield",
                    "Hookshot",
                    "Ice Arrow",
                    "Kafei's Mask",
                    "Kamaro's Mask",
                    "Keaton Mask",
                    "Kokiri Sword",
                    "Land Title Deed",
                    "Large Quiver",
                    "Largest Quiver",
                    "Lens of Truth",
                    "Letter to Kafei",
                    "Letter to Mama",
                    "Light Arrow",
                    "Magic Bean",
                    "Magic Power",
                    "Map of Clock Town",
                    "Map of Great Bay",
                    "Map of Romani Ranch",
                    "Map of Snowhead",
                    "Map of Stone Tower",
                    "Map of Woodfall",
                    "Mask of Scents",
                    "Mask of Truth",
                    "Milk",
                    "Mirror Shield",
                    "Moon's Tear",
                    "Mountain Title Deed",
                    "New Wave Bossa Nova",
                    "Oath to Order",
                    "Ocean Skulltula Spirit",
                    "Ocean Title Deed",
                    "Pendant of Memories",
                    "Pictobox",
                    "Piece of Heart",
                    "Postman's Hat",
                    "Powder Keg",
                    "Purple Rupee",
                    "Razor Sword",
                    "Red Potion",
                    "Red Rupee",
                    "Romani's Mask",
                    "Room Key",
                    "Seahorse",
                    "Silver Rupee",
                    "Snowhead Boss Key",
                    "Snowhead Compass",
                    "Snowhead Map",
                    "Snowhead Small Key",
                    "Snowhead Stray Fairy",
                    "Sonata of Awakening",
                    "Song of Healing",
                    "Song of Soaring",
                    "Song of Storms",
                    "Spin Attack",
                    "Stone Mask",
                    "Stone Tower Boss Key",
                    "Stone Tower Compass",
                    "Stone Tower Map",
                    "Stone Tower Small Key",
                    "Stone Tower Stray Fairy",
                    "Swamp Skulltula Spirit",
                    "Swamp Title Deed",
                    "Woodfall Boss Key",
                    "Woodfall Compass",
                    "Woodfall Map",
                    "Woodfall Small Key",
                    "Woodfall Stray Fairy",
                    "Zora Mask",
                ],
                locations: [
                    {name: "Aliens Defense", region: "RomaniRanch"},
                    {name: "All Night Mask Purchase", region: "WestClockTown"},
                    {name: "Anju and Kafei", region: "StockPotInn"},
                    {name: "Astronomy Telescope", region: "TerminaField"},
                    {name: "Baby Goron", region: "GoronVillage"},
                    {name: "Baby Zoras", region: "GreatBayCoast"},
                    {name: "Bad Pictograph of Lulu", region: "ZoraHall"},
                    {name: "Bank Reward #1", region: "WestClockTown"},
                    {name: "Bank Reward #2", region: "WestClockTown"},
                    {name: "Bank Reward #3", region: "WestClockTown"},
                    {name: "Bean Grotto", region: "DekuPalace"},
                    {name: "Bean Man", region: "DekuPalace"},
                    {name: "Beaver Race #1", region: "ZoraCape"},
                    {name: "Beaver Race #2", region: "ZoraCape"},
                    {name: "Behind Woodfall Owl Chest", region: "Woodfall"},
                    {name: "Big Bomb Bag Purchase", region: "WestClockTown"},
                    {name: "Biggest Bomb Bag Purchase", region: "GoronVillage"},
                    {name: "Bio Baba Grotto", region: "TerminaField"},
                    {name: "Boat Archery", region: "SouthernSwamp"},
                    {name: "Bomb Bag Purchase", region: "WestClockTown"},
                    {name: "Bomb Shop 10 Bombchu", region: "WestClockTown"},
                    {name: "Bomb Shop 10 Bombs", region: "WestClockTown"},
                    {name: "Bombers' Hide and Seek", region: "NorthClockTown"},
                    {name: "Bombers' Hideout Chest", region: "EastClockTown"},
                    {name: "Boss Blue Warp", region: "Misc"},
                    {name: "Bottle: Big Poe", region: "BottleCatch"},
                    {name: "Bottle: Bug", region: "BottleCatch"},
                    {name: "Bottle: Deku Princess", region: "BottleCatch"},
                    {name: "Bottle: Fairy", region: "BottleCatch"},
                    {name: "Bottle: Fish", region: "BottleCatch"},
                    {name: "Bottle: Hot Spring Water", region: "BottleCatch"},
                    {name: "Bottle: Mushroom", region: "BottleCatch"},
                    {name: "Bottle: Poe", region: "BottleCatch"},
                    {name: "Bottle: Spring Water", region: "BottleCatch"},
                    {name: "Bottle: Zora Egg", region: "BottleCatch"},
                    {name: "Business Scrub Purchase", region: "TerminaField"},
                    {name: "Butler", region: "DekuPalace"},
                    {name: "Canyon Scrub Purchase", region: "IkanaCanyon"},
                    {name: "Canyon Scrub Trade", region: "IkanaCanyon"},
                    {name: "Captain Keeta's Chest", region: "IkanaGraveyard"},
                    {name: "Clock Tower Entrance", region: "SouthClockTown"},
                    {name: "Clock Town Map Purchase", region: "NorthClockTown"},
                    {name: "Clock Town Scrub Trade", region: "SouthClockTown"},
                    {name: "Clock Town Stray Fairy", region: "LaundryPool"},
                    {name: "Cow Beneath the Well", region: "BeneathTheWell"},
                    {name: "Cremia", region: "RomaniRanch"},
                    {name: "Curiosity Shop Blue Rupee", region: "WestClockTown"},
                    {name: "Curiosity Shop Gold Rupee", region: "WestClockTown"},
                    {name: "Curiosity Shop Man #1", region: "LaundryPool"},
                    {name: "Curiosity Shop Man #2", region: "LaundryPool"},
                    {name: "Curiosity Shop Purple Rupee", region: "WestClockTown"},
                    {name: "Curiosity Shop Red Rupee", region: "WestClockTown"},
                    {name: "Dampe Digging", region: "IkanaGraveyard"},
                    {name: "Darmani", region: "MountainVillage"},
                    {name: "Day 1 Grave Bats", region: "IkanaGraveyard"},
                    {name: "Day 1 Grave Tablet", region: "IkanaGraveyard"},
                    {name: "Deku Palace West Garden", region: "DekuPalace"},
                    {name: "Deku Playground Any Day", region: "NorthClockTown"},
                    {name: "Deku Playground Three Days", region: "NorthClockTown"},
                    {name: "Deku Trial Bonus", region: "TheMoon"},
                    {name: "Dodongo Grotto", region: "TerminaField"},
                    {name: "Dog Race", region: "RomaniRanch"},
                    {name: "Doggy Racetrack Roof Chest", region: "RomaniRanch"},
                    {name: "East Clock Town Chest", region: "EastClockTown"},
                    {name: "Entrance to Woodfall Chest", region: "Woodfall"},
                    {name: "Evan", region: "ZoraHall"},
                    {name: "Fire Arrow Chest", region: "SnowheadTemple"},
                    {name: "Fisherman Game", region: "GreatBayCoast"},
                    {name: "Fisherman Pictograph", region: "GreatBayCoast"},
                    {name: "Frog Choir", region: "MountainVillage"},
                    {name: "Giant's Mask Chest", region: "StoneTowerTemple"},
                    {name: "Goht Heart Container", region: "SnowheadTemple"},
                    {name: "Good Pictograph of Lulu", region: "ZoraHall"},
                    {name: "Gorman Bros Milk Purchase", region: "MilkRoad"},
                    {name: "Gorman Bros Race", region: "MilkRoad"},
                    {name: "Gorman", region: "EastClockTown"},
                    {name: "Goron Race", region: "TwinIslands"},
                    {name: "Goron Racetrack Grotto", region: "TwinIslands"},
                    {name: "Goron Shop 10 Arrows", region: "GoronVillage"},
                    {name: "Goron Shop 10 Bombs", region: "GoronVillage"},
                    {name: "Goron Shop Red Potion", region: "GoronVillage"},
                    {name: "Goron Trial Bonus", region: "TheMoon"},
                    {name: "Goron Village Ledge", region: "GoronVillage"},
                    {name: "Gossip Stones", region: "TerminaField"},
                    {name: "Grandma Long Story", region: "StockPotInn"},
                    {name: "Grandma Short Story", region: "StockPotInn"},
                    {name: "Great Bay Bio Babas", region: "GreatBayTemple"},
                    {name: "Great Bay Boss Key Chest", region: "GreatBayTemple"},
                    {name: "Great Bay Coast Grotto Cow #1", region: "GreatBayCoast"},
                    {name: "Great Bay Coast Grotto Cow #2", region: "GreatBayCoast"},
                    {name: "Great Bay Coast Grotto", region: "GreatBayCoast"},
                    {name: "Great Bay Coast Ledge", region: "GreatBayCoast"},
                    {name: "Great Bay Compass Chest", region: "GreatBayTemple"},
                    {name: "Great Bay Dexihands Jar", region: "GreatBayTemple"},
                    {name: "Great Bay Entrance Torches", region: "GreatBayTemple"},
                    {name: "Great Bay Green Valve", region: "GreatBayTemple"},
                    {name: "Great Bay Ledge Jar", region: "GreatBayTemple"},
                    {name: "Great Bay Map Chest", region: "GreatBayTemple"},
                    {name: "Great Bay Map Purchase", region: "MilkRoad"},
                    {name: "Great Bay Pre-Boss Room Bubble", region: "GreatBayTemple"},
                    {name: "Great Bay Pre-Boss Room Underwater Bubble", region: "GreatBayTemple"},
                    {name: "Great Bay Seesaw Room", region: "GreatBayTemple"},
                    {name: "Great Bay Skulltula", region: "GreatBayTemple"},
                    {name: "Great Bay Small Key Chest", region: "GreatBayTemple"},
                    {name: "Great Bay Underwater Barrel", region: "GreatBayTemple"},
                    {name: "Great Bay Water Control Room Underwater Bubble", region: "GreatBayTemple"},
                    {name: "Great Bay Waterwheel Room Lower", region: "GreatBayTemple"},
                    {name: "Great Bay Waterwheel Room Upper", region: "GreatBayTemple"},
                    {name: "Great Bay Whirlpool Barrel", region: "GreatBayTemple"},
                    {name: "Great Bay Whirlpool Jar", region: "GreatBayTemple"},
                    {name: "Grog", region: "RomaniRanch"},
                    {name: "Guru Guru", region: "LaundryPool"},
                    {name: "Gyorg Heart Container", region: "GreatBayTemple"},
                    {name: "Hero's Bow Chest", region: "WoodfallTemple"},
                    {name: "Honey and Darling Any Day", region: "EastClockTown"},
                    {name: "Honey and Darling Three Days", region: "EastClockTown"},
                    {name: "Hookshot Chest", region: "PiratesFortressInterior"},
                    {name: "Hot Spring Water Grotto", region: "TwinIslands"},
                    {name: "Hungry Goron", region: "MountainVillage"},
                    {name: "Ice Arrow Chest", region: "GreatBayTemple"},
                    {name: "Ikana Canyon Ledge", region: "IkanaCanyon"},
                    {name: "Ikana Castle Pillar", region: "IkanaCastle"},
                    {name: "Ikana Graveyard Grotto", region: "IkanaGraveyard"},
                    {name: "Ikana Great Fairy", region: "IkanaCanyon"},
                    {name: "Ikana King", region: "IkanaCastle"},
                    {name: "Imprisoned Monkey", region: "DekuPalace"},
                    {name: "Inn Guest Room Chest", region: "StockPotInn"},
                    {name: "Inn Reservation", region: "StockPotInn"},
                    {name: "Inn Staff Room Chest", region: "StockPotInn"},
                    {name: "Inverted Stone Tower Left Chest", region: "StoneTower"},
                    {name: "Inverted Stone Tower Middle Chest", region: "StoneTower"},
                    {name: "Inverted Stone Tower Right Chest", region: "StoneTower"},
                    {name: "Invisible Soldier", region: "RoadToIkana"},
                    {name: "Iron Knuckle Chest", region: "IkanaGraveyard"},
                    {name: "Kafei", region: "LaundryPool"},
                    {name: "Kamaro", region: "TerminaField"},
                    {name: "Keaton Quiz", region: "NorthClockTown"},
                    {name: "Kotake Mushroom Sale", region: "SouthernSwamp"},
                    {name: "Kotake", region: "SouthernSwamp"},
                    {name: "Koume", region: "SouthernSwamp"},
                    {name: "Lab Fish", region: "GreatBayCoast"},
                    {name: "Lens Cave Invisible Chest", region: "GoronVillage"},
                    {name: "Lens Cave Rock Chest", region: "GoronVillage"},
                    {name: "Lens of Truth Chest", region: "GoronVillage"},
                    {name: "Light Arrow Chest", region: "StoneTowerTemple"},
                    {name: "Link Trial Bonus", region: "TheMoon"},
                    {name: "Link Trial Garo Master Chest", region: "TheMoon"},
                    {name: "Link Trial Iron Knuckle Chest", region: "TheMoon"},
                    {name: "Lottery", region: "WestClockTown"},
                    {name: "Lulu's Room Ledge", region: "ZoraHall"},
                    {name: "Madame Aroma in Bar", region: "EastClockTown"},
                    {name: "Madame Aroma in Office", region: "EastClockTown"},
                    {name: "Majora Child", region: "TheMoon"},
                    {name: "Mayor", region: "EastClockTown"},
                    {name: "Midnight Meeting", region: "StockPotInn"},
                    {name: "Mikau", region: "GreatBayCoast"},
                    {name: "Milk Bar Chateau", region: "EastClockTown"},
                    {name: "Milk Bar Milk", region: "EastClockTown"},
                    {name: "Mirror Shield Chest", region: "BeneathTheWell"},
                    {name: "Mountain Scrub Trade", region: "GoronVillage"},
                    {name: "Mountain Smithy Day 1", region: "MountainVillage"},
                    {name: "Mountain Smithy Day 2", region: "MountainVillage"},
                    {name: "Mountain Spring Grotto", region: "MountainVillage"},
                    {name: "Mountain Waterfall Chest", region: "MountainVillage"},
                    {name: "Mystery Woods Grotto", region: "SouthernSwamp"},
                    {name: "Near Swamp Spider House Grotto", region: "SouthernSwamp"},
                    {name: "North Clock Town Tree", region: "NorthClockTown"},
                    {name: "Ocean Great Fairy", region: "ZoraCape"},
                    {name: "Ocean Scrub Purchase", region: "ZoraHall"},
                    {name: "Ocean Scrub Trade", region: "ZoraHall"},
                    {name: "Ocean Skulltula 2nd Room Behind Skull 1", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Behind Skull 2", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Ceiling Edge", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Ceiling Plank", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Jar", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Lower Pot", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Upper Pot", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Webbed Hole", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula 2nd Room Webbed Pot", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Colored Skulls Behind Picture", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Colored Skulls Ceiling Edge", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Colored Skulls Chandelier 1", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Colored Skulls Chandelier 2", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Colored Skulls Chandelier 3", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Colored Skulls Pot", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Entrance Left Wall", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Entrance Right Wall", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Entrance Web", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library Behind Bookcase 1", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library Behind Bookcase 2", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library Behind Picture", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library Ceiling Edge", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library Hole Behind Cabinet", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library Hole Behind Picture", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Library On Corner Bookshelf", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Storage Room Behind Boat", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Storage Room Behind Crate", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Storage Room Ceiling Web", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Storage Room Crate", region: "GreatBayCoast"},
                    {name: "Ocean Skulltula Storage Room Jar", region: "GreatBayCoast"},
                    {name: "Ocean Spider House Chest", region: "GreatBayCoast"},
                    {name: "Ocean Spider House Day 1 Reward", region: "GreatBayCoast"},
                    {name: "Ocean Spider House Day 2 Reward", region: "GreatBayCoast"},
                    {name: "Ocean Spider House Day 3 Reward", region: "GreatBayCoast"},
                    {name: "Odolwa Heart Container", region: "WoodfallTemple"},
                    {name: "Old Lady", region: "NorthClockTown"},
                    {name: "Pamela's Father", region: "IkanaCanyon"},
                    {name: "Path to Ikana Grotto", region: "RoadToIkana"},
                    {name: "Path to Ikana Pillar Chest", region: "RoadToIkana"},
                    {name: "Path to Snowhead Grotto", region: "PathToSnowhead"},
                    {name: "Path to Snowhead Pillar", region: "PathToSnowhead"},
                    {name: "Path to Swamp Grotto", region: "RoadToSouthernSwamp"},
                    {name: "Path to Swamp Tree", region: "RoadToSouthernSwamp"},
                    {name: "Peahat Grotto", region: "TerminaField"},
                    {name: "Pictograph Contest Good Photo", region: "SouthernSwamp"},
                    {name: "Pictograph Contest Standard Photo", region: "SouthernSwamp"},
                    {name: "Pictograph Contest Winner", region: "SouthernSwamp"},
                    {name: "Pinnacle Rock Lower Chest", region: "PinnacleRock"},
                    {name: "Pinnacle Rock Upper Chest", region: "PinnacleRock"},
                    {name: "Pirates' Fortress Cage Room Deep Chest", region: "PiratesFortressSewer"},
                    {name: "Pirates' Fortress Cage Room Shallow Chest", region: "PiratesFortressSewer"},
                    {name: "Pirates' Fortress Cage", region: "PiratesFortressSewer"},
                    {name: "Pirates' Fortress Exterior Corner Chest", region: "PiratesFortressExterior"},
                    {name: "Pirates' Fortress Exterior Log Chest", region: "PiratesFortressExterior"},
                    {name: "Pirates' Fortress Exterior Sand Chest", region: "PiratesFortressExterior"},
                    {name: "Pirates' Fortress Interior Guard Room Chest", region: "PiratesFortressInterior"},
                    {name: "Pirates' Fortress Interior Lower Chest", region: "PiratesFortressInterior"},
                    {name: "Pirates' Fortress Interior Tank Chest", region: "PiratesFortressInterior"},
                    {name: "Pirates' Fortress Interior Upper Chest", region: "PiratesFortressInterior"},
                    {name: "Pirates' Fortress Maze Chest", region: "PiratesFortressSewer"},
                    {name: "Poe Hut", region: "IkanaCanyon"},
                    {name: "Postbox", region: "SouthClockTown"},
                    {name: "Postman's Freedom Reward", region: "EastClockTown"},
                    {name: "Postman's Game", region: "WestClockTown"},
                    {name: "Powder Keg Challenge", region: "GoronVillage"},
                    {name: "Pre-Clocktown Chest", region: "BeneathClocktown"},
                    {name: "Ranch Cow #1", region: "RomaniRanch"},
                    {name: "Ranch Cow #2", region: "RomaniRanch"},
                    {name: "Ranch Cow #3", region: "RomaniRanch"},
                    {name: "Romani Ranch Map Purchase", region: "MilkRoad"},
                    {name: "Romani's Game", region: "RomaniRanch"},
                    {name: "Rosa Sisters", region: "WestClockTown"},
                    {name: "Seahorses", region: "PinnacleRock"},
                    {name: "Secret Shrine Dinolfos Chest", region: "SecretShrine"},
                    {name: "Secret Shrine Final Chest", region: "SecretShrine"},
                    {name: "Secret Shrine Garo Master Chest", region: "SecretShrine"},
                    {name: "Secret Shrine Grotto", region: "IkanaCanyon"},
                    {name: "Secret Shrine Wart Chest", region: "SecretShrine"},
                    {name: "Secret Shrine Wizzrobe Chest", region: "SecretShrine"},
                    {name: "Snowhead Basement", region: "SnowheadTemple"},
                    {name: "Snowhead Block Room Chest", region: "SnowheadTemple"},
                    {name: "Snowhead Boss Key Chest", region: "SnowheadTemple"},
                    {name: "Snowhead Bridge Room Chest", region: "SnowheadTemple"},
                    {name: "Snowhead Bridge Room Ledge Bubble", region: "SnowheadTemple"},
                    {name: "Snowhead Bridge Room Pillar Bubble", region: "SnowheadTemple"},
                    {name: "Snowhead Ceiling Bubble", region: "SnowheadTemple"},
                    {name: "Snowhead Compass Chest", region: "SnowheadTemple"},
                    {name: "Snowhead Crate", region: "SnowheadTemple"},
                    {name: "Snowhead Dinolfos 1", region: "SnowheadTemple"},
                    {name: "Snowhead Dinolfos 2", region: "SnowheadTemple"},
                    {name: "Snowhead Great Fairy", region: "Snowhead"},
                    {name: "Snowhead Ice Puzzle", region: "SnowheadTemple"},
                    {name: "Snowhead Icicle Room Chest", region: "SnowheadTemple"},
                    {name: "Snowhead Icicle Room Wall", region: "SnowheadTemple"},
                    {name: "Snowhead Main Room Wall", region: "SnowheadTemple"},
                    {name: "Snowhead Map Chest", region: "SnowheadTemple"},
                    {name: "Snowhead Map Purchase", region: "RoadToSouthernSwamp"},
                    {name: "Snowhead Map Room Fairy", region: "SnowheadTemple"},
                    {name: "Snowhead Map Room Ledge", region: "SnowheadTemple"},
                    {name: "Snowhead Pillar Freezards", region: "SnowheadTemple"},
                    {name: "Snowhead Snow Room Bubble", region: "SnowheadTemple"},
                    {name: "Snowhead Twin Block", region: "SnowheadTemple"},
                    {name: "South Clock Town Final Day Chest", region: "SouthClockTown"},
                    {name: "South Clock Town Straw Roof Chest", region: "SouthClockTown"},
                    {name: "Starting Heart Container #1", region: "Misc"},
                    {name: "Starting Heart Container #2", region: "Misc"},
                    {name: "Starting Item", region: "Misc"},
                    {name: "Starting Shield", region: "Misc"},
                    {name: "Starting Song", region: "Misc"},
                    {name: "Starting Sword", region: "Misc"},
                    {name: "Stone Tower Armor Room Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Basement Ledge", region: "StoneTowerTemple"},
                    {name: "Stone Tower Boss Key Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Boss Warp", region: "StoneTowerTemple"},
                    {name: "Stone Tower Bridge Crystal", region: "StoneTowerTemple"},
                    {name: "Stone Tower Compass Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Death Armos Maze Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Death Armos", region: "StoneTowerTemple"},
                    {name: "Stone Tower Eyegore Room Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Eyegore", region: "StoneTowerTemple"},
                    {name: "Stone Tower Lava Room Fire Ring", region: "StoneTowerTemple"},
                    {name: "Stone Tower Lava Room Ledge", region: "StoneTowerTemple"},
                    {name: "Stone Tower Map Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Map Purchase", region: "GreatBayCoast"},
                    {name: "Stone Tower Mirror Sun Block", region: "StoneTowerTemple"},
                    {name: "Stone Tower Mirror Sun Switch", region: "StoneTowerTemple"},
                    {name: "Stone Tower Statue Eye", region: "StoneTowerTemple"},
                    {name: "Stone Tower Thin Bridge", region: "StoneTowerTemple"},
                    {name: "Stone Tower Underwater", region: "StoneTowerTemple"},
                    {name: "Stone Tower Updraft Fire Ring", region: "StoneTowerTemple"},
                    {name: "Stone Tower Updraft Frozen Eye", region: "StoneTowerTemple"},
                    {name: "Stone Tower Updraft Room Chest", region: "StoneTowerTemple"},
                    {name: "Stone Tower Wizzrobe", region: "StoneTowerTemple"},
                    {name: "Swamp Archery #1", region: "RoadToSouthernSwamp"},
                    {name: "Swamp Archery #2", region: "RoadToSouthernSwamp"},
                    {name: "Swamp Music Statue", region: "SouthernSwamp"},
                    {name: "Swamp Scrub Purchase", region: "SouthernSwamp"},
                    {name: "Swamp Scrub Trade", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Gold Room Hive", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Gold Room Near Ceiling", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Gold Room Pillar", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Gold Room Wall", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Jar", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Lower Left Soft Soil", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Lower Right Soft Soil", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Near Ceiling", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Pillar", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Upper Pillar", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Upper Soft Soil", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Main Room Water", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Monument Room Crate 1", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Monument Room Crate 2", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Monument Room Lower Wall", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Monument Room On Monument", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Monument Room Torch", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Behind Vines", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Hive 1", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Hive 2", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Jar", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Pot 1", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Pot 2", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Pot Room Wall", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Tree Room Grass 1", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Tree Room Grass 2", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Tree Room Hive", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Tree Room Tree 1", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Tree Room Tree 2", region: "SouthernSwamp"},
                    {name: "Swamp Skulltula Tree Room Tree 3", region: "SouthernSwamp"},
                    {name: "Swamp Spider House Reward", region: "SouthernSwamp"},
                    {name: "Swamp Tourist Center Roof", region: "SouthernSwamp"},
                    {name: "Swordsman's School", region: "WestClockTown"},
                    {name: "Termina Field Grass Chest", region: "TerminaField"},
                    {name: "Termina Field Grass Grotto", region: "TerminaField"},
                    {name: "Termina Field Pillar Grotto", region: "TerminaField"},
                    {name: "Termina Field Stump Chest", region: "TerminaField"},
                    {name: "Termina Field Underwater Chest", region: "TerminaField"},
                    {name: "Termina Grotto Cow #1", region: "TerminaField"},
                    {name: "Termina Grotto Cow #2", region: "TerminaField"},
                    {name: "Toilet Hand", region: "StockPotInn"},
                    {name: "Town Archery #1", region: "EastClockTown"},
                    {name: "Town Archery #2", region: "EastClockTown"},
                    {name: "Town Great Fairy Non-Human", region: "NorthClockTown"},
                    {name: "Town Great Fairy", region: "NorthClockTown"},
                    {name: "Trading Post 10 Deku Nuts", region: "WestClockTown"},
                    {name: "Trading Post 30 Arrows", region: "WestClockTown"},
                    {name: "Trading Post 50 Arrows", region: "WestClockTown"},
                    {name: "Trading Post Deku Stick", region: "WestClockTown"},
                    {name: "Trading Post Fairy", region: "WestClockTown"},
                    {name: "Trading Post Green Potion", region: "WestClockTown"},
                    {name: "Trading Post Hero's Shield", region: "WestClockTown"},
                    {name: "Trading Post Red Potion", region: "WestClockTown"},
                    {name: "Treasure Chest Game Deku", region: "EastClockTown"},
                    {name: "Treasure Chest Game Goron", region: "EastClockTown"},
                    {name: "Treasure Chest Game Human", region: "EastClockTown"},
                    {name: "Treasure Chest Game Zora", region: "EastClockTown"},
                    {name: "Twin Islands Cave Chest", region: "TwinIslands"},
                    {name: "Twin Islands Underwater Ramp Chest", region: "TwinIslands"},
                    {name: "Twinmold Heart Container", region: "StoneTowerTemple"},
                    {name: "Well Left Path Chest", region: "BeneathTheWell"},
                    {name: "Well Right Path Chest", region: "BeneathTheWell"},
                    {name: "Witch Shop Blue Potion", region: "SouthernSwamp"},
                    {name: "Witch Shop Green Potion", region: "SouthernSwamp"},
                    {name: "Witch Shop Red Potion", region: "SouthernSwamp"},
                    {name: "Woodfall Boss Key Chest", region: "WoodfallTemple"},
                    {name: "Woodfall Bridge Chest", region: "Woodfall"},
                    {name: "Woodfall Bridge Room Hive", region: "WoodfallTemple"},
                    {name: "Woodfall Compass Chest", region: "WoodfallTemple"},
                    {name: "Woodfall Dark Room", region: "WoodfallTemple"},
                    {name: "Woodfall Deku Baba", region: "WoodfallTemple"},
                    {name: "Woodfall Entrance Fairy", region: "WoodfallTemple"},
                    {name: "Woodfall Entrance Platform", region: "WoodfallTemple"},
                    {name: "Woodfall Great Fairy", region: "Woodfall"},
                    {name: "Woodfall Jar Fairy", region: "WoodfallTemple"},
                    {name: "Woodfall Main Room Bubble", region: "WoodfallTemple"},
                    {name: "Woodfall Main Room Switch", region: "WoodfallTemple"},
                    {name: "Woodfall Map Chest", region: "WoodfallTemple"},
                    {name: "Woodfall Map Purchase", region: "RoadToSouthernSwamp"},
                    {name: "Woodfall Platform Room Hive", region: "WoodfallTemple"},
                    {name: "Woodfall Poison Water Bubble", region: "WoodfallTemple"},
                    {name: "Woodfall Pre-Boss Lower Right Bubble", region: "WoodfallTemple"},
                    {name: "Woodfall Pre-Boss Pillar Bubble", region: "WoodfallTemple"},
                    {name: "Woodfall Pre-Boss Upper Left Bubble", region: "WoodfallTemple"},
                    {name: "Woodfall Pre-Boss Upper Right Bubble", region: "WoodfallTemple"},
                    {name: "Woodfall Skulltula", region: "WoodfallTemple"},
                    {name: "Woodfall Small Key Chest", region: "WoodfallTemple"},
                    {name: "Zora Cape Grotto", region: "ZoraCape"},
                    {name: "Zora Cape Ledge With Tree Chest", region: "ZoraCape"},
                    {name: "Zora Cape Ledge Without Tree Chest", region: "ZoraCape"},
                    {name: "Zora Cape Like-Like", region: "ZoraCape"},
                    {name: "Zora Cape Underwater Chest", region: "ZoraCape"},
                    {name: "Zora Hall Stage Lights", region: "ZoraHall"},
                    {name: "Zora Shop 10 Arrows", region: "ZoraHall"},
                    {name: "Zora Shop Hero's Shield", region: "ZoraHall"},
                    {name: "Zora Shop Red Potion", region: "ZoraHall"},
                    {name: "Zora Trial Bonus", region: "TheMoon"},
                ],
                showNotification: false,
                message: null,
                regionHints: {},
                showDeleteModal: false,
            };
        },
        created() {
            let hints = JSON.parse(localStorage.getItem("regionHints"));
            if (hints) {
                this.regionHints = hints;
            }
        },
        methods: {
            handleLocationSelect(location) {
                if (Object.entries(location).length === 0) {
                    this.selectedLocation = {};
                    return;
                }
                this.selectedLocation = location;
            },
            handleItemSelect(item) {
                if (!item) {
                    this.selectedItem = null;
                    return;
                }
                this.selectedItem = item;
            },
            handleNotificationClose() {
                this.showNotification = false;
                this.message = null;
                this.timeOutId = null;
            },
            addHint() {
                if (!this.regionHints[this.selectedLocation.region]) {
                    this.regionHints[this.selectedLocation.region] = [{
                        locationName: this.selectedLocation.name,
                        item: this.selectedItem,
                    }];
                } else {
                    this.regionHints[this.selectedLocation.region].push({
                        locationName: this.selectedLocation.name,
                        item: this.selectedItem,
                    });
                }
                this.showNotification = true;
                this.message = `Added New Hint. ${this.selectedLocation.name} is ${this.selectedItem}.`;
                if (this.timeOutId !== null) {
                    clearTimeout(this.timeOutId);
                    this.timeOutId = null;
                }
                this.timeOutId = setTimeout(() => {
                    this.showNotification = false;
                    this.message = null;
                }, 3000);

                this.selectedLocation = {};
                this.selectedItem = null;
                localStorage.setItem("regionHints", JSON.stringify(this.regionHints));
            },
            removeHint(region, hint) {
                for (let i in this.regionHints[region]) {
                    if (Object.prototype.hasOwnProperty.call(this.regionHints[region], i) && this.regionHints[region][i].item === hint.item) {
                        this.regionHints[region].splice(i, 1);
                    }
                }
                if (this.regionHints[region].length === 0) {
                    this.$delete(this.regionHints, region);
                }
            },
            splitRegionName(region){
                return region.split(/(?=[A-Z])/).join(" ");
            },
            resetRegionHints() {
                this.regionHints = {};
                localStorage.clear();
                this.showDeleteModal = false;
            },
        },
    };
</script>

<style scoped>

</style>
